import Foundation

struct Country: Identifiable, Hashable {
    var id: String { isoCode }
    let isoCode: String
    let name: String
    let dialCode: String
    let flag: String
    
    static let allCountries: [Country] = [
        Country(isoCode: "AF", name: "Afghanistan", dialCode: "+93", flag: "🇦🇫"),
        Country(isoCode: "AL", name: "Albania", dialCode: "+355", flag: "🇦🇱"),
        Country(isoCode: "DZ", name: "Algeria", dialCode: "+213", flag: "🇩🇿"),
        Country(isoCode: "AS", name: "American Samoa", dialCode: "+1", flag: "🇦🇸"),
        Country(isoCode: "AD", name: "Andorra", dialCode: "+376", flag: "🇦🇩"),
        Country(isoCode: "AO", name: "Angola", dialCode: "+244", flag: "🇦🇴"),
        Country(isoCode: "AI", name: "Anguilla", dialCode: "+1", flag: "🇦🇮"),
        Country(isoCode: "AG", name: "Antigua and Barbuda", dialCode: "+1", flag: "🇦🇬"),
        Country(isoCode: "AR", name: "Argentina", dialCode: "+54", flag: "🇦🇷"),
        Country(isoCode: "AM", name: "Armenia", dialCode: "+374", flag: "🇦🇲"),
        Country(isoCode: "AW", name: "Aruba", dialCode: "+297", flag: "🇦🇼"),
        Country(isoCode: "AU", name: "Australia", dialCode: "+61", flag: "🇦🇺"),
        Country(isoCode: "AT", name: "Austria", dialCode: "+43", flag: "🇦🇹"),
        Country(isoCode: "AZ", name: "Azerbaijan", dialCode: "+994", flag: "🇦🇿"),
        Country(isoCode: "BS", name: "Bahamas", dialCode: "+1", flag: "🇧🇸"),
        Country(isoCode: "BH", name: "Bahrain", dialCode: "+973", flag: "🇧🇭"),
        Country(isoCode: "BD", name: "Bangladesh", dialCode: "+880", flag: "🇧🇩"),
        Country(isoCode: "BB", name: "Barbados", dialCode: "+1", flag: "🇧🇧"),
        Country(isoCode: "BY", name: "Belarus", dialCode: "+375", flag: "🇧🇾"),
        Country(isoCode: "BE", name: "Belgium", dialCode: "+32", flag: "🇧🇪"),
        Country(isoCode: "BZ", name: "Belize", dialCode: "+501", flag: "🇧🇿"),
        Country(isoCode: "BJ", name: "Benin", dialCode: "+229", flag: "🇧🇯"),
        Country(isoCode: "BM", name: "Bermuda", dialCode: "+1", flag: "🇧🇲"),
        Country(isoCode: "BT", name: "Bhutan", dialCode: "+975", flag: "🇧🇹"),
        Country(isoCode: "BO", name: "Bolivia", dialCode: "+591", flag: "🇧🇴"),
        Country(isoCode: "BA", name: "Bosnia and Herzegovina", dialCode: "+387", flag: "🇧🇦"),
        Country(isoCode: "BW", name: "Botswana", dialCode: "+267", flag: "🇧🇼"),
        Country(isoCode: "BR", name: "Brazil", dialCode: "+55", flag: "🇧🇷"),
        Country(isoCode: "IO", name: "British Indian Ocean Territory", dialCode: "+246", flag: "🇮🇴"),
        Country(isoCode: "VG", name: "British Virgin Islands", dialCode: "+1", flag: "🇻🇬"),
        Country(isoCode: "BN", name: "Brunei", dialCode: "+673", flag: "🇧🇳"),
        Country(isoCode: "BG", name: "Bulgaria", dialCode: "+359", flag: "🇧🇬"),
        Country(isoCode: "BF", name: "Burkina Faso", dialCode: "+226", flag: "🇧🇫"),
        Country(isoCode: "BI", name: "Burundi", dialCode: "+257", flag: "🇧🇮"),
        Country(isoCode: "KH", name: "Cambodia", dialCode: "+855", flag: "🇰🇭"),
        Country(isoCode: "CM", name: "Cameroon", dialCode: "+237", flag: "🇨🇲"),
        Country(isoCode: "CA", name: "Canada", dialCode: "+1", flag: "🇨🇦"),
        Country(isoCode: "CV", name: "Cape Verde", dialCode: "+238", flag: "🇨🇻"),
        Country(isoCode: "KY", name: "Cayman Islands", dialCode: "+1", flag: "🇰🇾"),
        Country(isoCode: "CF", name: "Central African Republic", dialCode: "+236", flag: "🇨🇫"),
        Country(isoCode: "TD", name: "Chad", dialCode: "+235", flag: "🇹🇩"),
        Country(isoCode: "CL", name: "Chile", dialCode: "+56", flag: "🇨🇱"),
        Country(isoCode: "CN", name: "China", dialCode: "+86", flag: "🇨🇳"),
        Country(isoCode: "CX", name: "Christmas Island", dialCode: "+61", flag: "🇨🇽"),
        Country(isoCode: "CC", name: "Cocos Islands", dialCode: "+61", flag: "🇨🇨"),
        Country(isoCode: "CO", name: "Colombia", dialCode: "+57", flag: "🇨🇴"),
        Country(isoCode: "KM", name: "Comoros", dialCode: "+269", flag: "🇰🇲"),
        Country(isoCode: "CK", name: "Cook Islands", dialCode: "+682", flag: "🇨🇰"),
        Country(isoCode: "CR", name: "Costa Rica", dialCode: "+506", flag: "🇨🇷"),
        Country(isoCode: "HR", name: "Croatia", dialCode: "+385", flag: "🇭🇷"),
        Country(isoCode: "CU", name: "Cuba", dialCode: "+53", flag: "🇨🇺"),
        Country(isoCode: "CW", name: "Curacao", dialCode: "+599", flag: "🇨🇼"),
        Country(isoCode: "CY", name: "Cyprus", dialCode: "+357", flag: "🇨🇾"),
        Country(isoCode: "CZ", name: "Czech Republic", dialCode: "+420", flag: "🇨🇿"),
        Country(isoCode: "CD", name: "Democratic Republic of the Congo", dialCode: "+243", flag: "🇨🇩"),
        Country(isoCode: "DK", name: "Denmark", dialCode: "+45", flag: "🇩🇰"),
        Country(isoCode: "DJ", name: "Djibouti", dialCode: "+253", flag: "🇩🇯"),
        Country(isoCode: "DM", name: "Dominica", dialCode: "+1", flag: "🇩🇲"),
        Country(isoCode: "DO", name: "Dominican Republic", dialCode: "+1", flag: "🇩🇴"),
        Country(isoCode: "TL", name: "East Timor", dialCode: "+670", flag: "🇹🇱"),
        Country(isoCode: "EC", name: "Ecuador", dialCode: "+593", flag: "🇪🇨"),
        Country(isoCode: "EG", name: "Egypt", dialCode: "+20", flag: "🇪🇬"),
        Country(isoCode: "SV", name: "El Salvador", dialCode: "+503", flag: "🇸🇻"),
        Country(isoCode: "GQ", name: "Equatorial Guinea", dialCode: "+240", flag: "🇬🇶"),
        Country(isoCode: "ER", name: "Eritrea", dialCode: "+291", flag: "🇪🇷"),
        Country(isoCode: "EE", name: "Estonia", dialCode: "+372", flag: "🇪🇪"),
        Country(isoCode: "ET", name: "Ethiopia", dialCode: "+251", flag: "🇪🇹"),
        Country(isoCode: "FK", name: "Falkland Islands", dialCode: "+500", flag: "🇫🇰"),
        Country(isoCode: "FO", name: "Faroe Islands", dialCode: "+298", flag: "🇫🇴"),
        Country(isoCode: "FJ", name: "Fiji", dialCode: "+679", flag: "🇫🇯"),
        Country(isoCode: "FI", name: "Finland", dialCode: "+358", flag: "🇫🇮"),
        Country(isoCode: "FR", name: "France", dialCode: "+33", flag: "🇫🇷"),
        Country(isoCode: "PF", name: "French Polynesia", dialCode: "+689", flag: "🇵🇫"),
        Country(isoCode: "GA", name: "Gabon", dialCode: "+241", flag: "🇬🇦"),
        Country(isoCode: "GM", name: "Gambia", dialCode: "+220", flag: "🇬🇲"),
        Country(isoCode: "GE", name: "Georgia", dialCode: "+995", flag: "🇬🇪"),
        Country(isoCode: "DE", name: "Germany", dialCode: "+49", flag: "🇩🇪"),
        Country(isoCode: "GH", name: "Ghana", dialCode: "+233", flag: "🇬🇭"),
        Country(isoCode: "GI", name: "Gibraltar", dialCode: "+350", flag: "🇬🇮"),
        Country(isoCode: "GR", name: "Greece", dialCode: "+30", flag: "🇬🇷"),
        Country(isoCode: "GL", name: "Greenland", dialCode: "+299", flag: "🇬🇱"),
        Country(isoCode: "GD", name: "Grenada", dialCode: "+1", flag: "🇬🇩"),
        Country(isoCode: "GU", name: "Guam", dialCode: "+1", flag: "🇬🇺"),
        Country(isoCode: "GT", name: "Guatemala", dialCode: "+502", flag: "🇬🇹"),
        Country(isoCode: "GG", name: "Guernsey", dialCode: "+44", flag: "🇬🇬"),
        Country(isoCode: "GN", name: "Guinea", dialCode: "+224", flag: "🇬🇳"),
        Country(isoCode: "GW", name: "Guinea-Bissau", dialCode: "+245", flag: "🇬🇼"),
        Country(isoCode: "GY", name: "Guyana", dialCode: "+592", flag: "🇬🇾"),
        Country(isoCode: "HT", name: "Haiti", dialCode: "+509", flag: "🇭🇹"),
        Country(isoCode: "HN", name: "Honduras", dialCode: "+504", flag: "🇭🇳"),
        Country(isoCode: "HK", name: "Hong Kong", dialCode: "+852", flag: "🇭🇰"),
        Country(isoCode: "HU", name: "Hungary", dialCode: "+36", flag: "🇭🇺"),
        Country(isoCode: "IS", name: "Iceland", dialCode: "+354", flag: "🇮🇸"),
        Country(isoCode: "IN", name: "India", dialCode: "+91", flag: "🇮🇳"),
        Country(isoCode: "ID", name: "Indonesia", dialCode: "+62", flag: "🇮🇩"),
        Country(isoCode: "IR", name: "Iran", dialCode: "+98", flag: "🇮🇷"),
        Country(isoCode: "IQ", name: "Iraq", dialCode: "+964", flag: "🇮🇶"),
        Country(isoCode: "IE", name: "Ireland", dialCode: "+353", flag: "🇮🇪"),
        Country(isoCode: "IM", name: "Isle of Man", dialCode: "+44", flag: "🇮🇲"),
        Country(isoCode: "IL", name: "Israel", dialCode: "+972", flag: "🇮🇱"),
        Country(isoCode: "IT", name: "Italy", dialCode: "+39", flag: "🇮🇹"),
        Country(isoCode: "CI", name: "Ivory Coast", dialCode: "+225", flag: "🇨🇮"),
        Country(isoCode: "JM", name: "Jamaica", dialCode: "+1", flag: "🇯🇲"),
        Country(isoCode: "JP", name: "Japan", dialCode: "+81", flag: "🇯🇵"),
        Country(isoCode: "JE", name: "Jersey", dialCode: "+44", flag: "🇯🇪"),
        Country(isoCode: "JO", name: "Jordan", dialCode: "+962", flag: "🇯🇴"),
        Country(isoCode: "KZ", name: "Kazakhstan", dialCode: "+7", flag: "🇰🇿"),
        Country(isoCode: "KE", name: "Kenya", dialCode: "+254", flag: "🇰🇪"),
        Country(isoCode: "KI", name: "Kiribati", dialCode: "+686", flag: "🇰🇮"),
        Country(isoCode: "XK", name: "Kosovo", dialCode: "+383", flag: "🇽🇰"),
        Country(isoCode: "KW", name: "Kuwait", dialCode: "+965", flag: "🇰🇼"),
        Country(isoCode: "KG", name: "Kyrgyzstan", dialCode: "+996", flag: "🇰🇬"),
        Country(isoCode: "LA", name: "Laos", dialCode: "+856", flag: "🇱🇦"),
        Country(isoCode: "LV", name: "Latvia", dialCode: "+371", flag: "🇱🇻"),
        Country(isoCode: "LB", name: "Lebanon", dialCode: "+961", flag: "🇱🇧"),
        Country(isoCode: "LS", name: "Lesotho", dialCode: "+266", flag: "🇱🇸"),
        Country(isoCode: "LR", name: "Liberia", dialCode: "+231", flag: "🇱🇷"),
        Country(isoCode: "LY", name: "Libya", dialCode: "+218", flag: "🇱🇾"),
        Country(isoCode: "LI", name: "Liechtenstein", dialCode: "+423", flag: "🇱🇮"),
        Country(isoCode: "LT", name: "Lithuania", dialCode: "+370", flag: "🇱🇹"),
        Country(isoCode: "LU", name: "Luxembourg", dialCode: "+352", flag: "🇱🇺"),
        Country(isoCode: "MO", name: "Macau", dialCode: "+853", flag: "🇲🇴"),
        Country(isoCode: "MK", name: "Macedonia", dialCode: "+389", flag: "🇲🇰"),
        Country(isoCode: "MG", name: "Madagascar", dialCode: "+261", flag: "🇲🇬"),
        Country(isoCode: "MW", name: "Malawi", dialCode: "+265", flag: "🇲🇼"),
        Country(isoCode: "MY", name: "Malaysia", dialCode: "+60", flag: "🇲🇾"),
        Country(isoCode: "MV", name: "Maldives", dialCode: "+960", flag: "🇲🇻"),
        Country(isoCode: "ML", name: "Mali", dialCode: "+223", flag: "🇲🇱"),
        Country(isoCode: "MT", name: "Malta", dialCode: "+356", flag: "🇲🇹"),
        Country(isoCode: "MH", name: "Marshall Islands", dialCode: "+692", flag: "🇲🇭"),
        Country(isoCode: "MR", name: "Mauritania", dialCode: "+222", flag: "🇲🇷"),
        Country(isoCode: "MU", name: "Mauritius", dialCode: "+230", flag: "🇲🇺"),
        Country(isoCode: "YT", name: "Mayotte", dialCode: "+262", flag: "🇾🇹"),
        Country(isoCode: "MX", name: "Mexico", dialCode: "+52", flag: "🇲🇽"),
        Country(isoCode: "FM", name: "Micronesia", dialCode: "+691", flag: "🇫🇲"),
        Country(isoCode: "MD", name: "Moldova", dialCode: "+373", flag: "🇲🇩"),
        Country(isoCode: "MC", name: "Monaco", dialCode: "+377", flag: "🇲🇨"),
        Country(isoCode: "MN", name: "Mongolia", dialCode: "+976", flag: "🇲🇳"),
        Country(isoCode: "ME", name: "Montenegro", dialCode: "+382", flag: "🇲🇪"),
        Country(isoCode: "MS", name: "Montserrat", dialCode: "+1", flag: "🇲🇸"),
        Country(isoCode: "MA", name: "Morocco", dialCode: "+212", flag: "🇲🇦"),
        Country(isoCode: "MZ", name: "Mozambique", dialCode: "+258", flag: "🇲🇿"),
        Country(isoCode: "MM", name: "Myanmar", dialCode: "+95", flag: "🇲🇲"),
        Country(isoCode: "NA", name: "Namibia", dialCode: "+264", flag: "🇳🇦"),
        Country(isoCode: "NR", name: "Nauru", dialCode: "+674", flag: "🇳🇷"),
        Country(isoCode: "NP", name: "Nepal", dialCode: "+977", flag: "🇳🇵"),
        Country(isoCode: "NL", name: "Netherlands", dialCode: "+31", flag: "🇳🇱"),
        Country(isoCode: "AN", name: "Netherlands Antilles", dialCode: "+599", flag: "🇦🇳"),
        Country(isoCode: "NC", name: "New Caledonia", dialCode: "+687", flag: "🇳🇨"),
        Country(isoCode: "NZ", name: "New Zealand", dialCode: "+64", flag: "🇳🇿"),
        Country(isoCode: "NI", name: "Nicaragua", dialCode: "+505", flag: "🇳🇮"),
        Country(isoCode: "NE", name: "Niger", dialCode: "+227", flag: "🇳🇪"),
        Country(isoCode: "NG", name: "Nigeria", dialCode: "+234", flag: "🇳🇬"),
        Country(isoCode: "NU", name: "Niue", dialCode: "+683", flag: "🇳🇺"),
        Country(isoCode: "KP", name: "North Korea", dialCode: "+850", flag: "🇰🇵"),
        Country(isoCode: "MP", name: "Northern Mariana Islands", dialCode: "+1", flag: "🇲🇵"),
        Country(isoCode: "NO", name: "Norway", dialCode: "+47", flag: "🇳🇴"),
        Country(isoCode: "OM", name: "Oman", dialCode: "+968", flag: "🇴🇲"),
        Country(isoCode: "PK", name: "Pakistan", dialCode: "+92", flag: "🇵🇰"),
        Country(isoCode: "PW", name: "Palau", dialCode: "+680", flag: "🇵🇼"),
        Country(isoCode: "PS", name: "Palestine", dialCode: "+970", flag: "🇵🇸"),
        Country(isoCode: "PA", name: "Panama", dialCode: "+507", flag: "🇵🇦"),
        Country(isoCode: "PG", name: "Papua New Guinea", dialCode: "+675", flag: "🇵🇬"),
        Country(isoCode: "PY", name: "Paraguay", dialCode: "+595", flag: "🇵🇾"),
        Country(isoCode: "PE", name: "Peru", dialCode: "+51", flag: "🇵🇪"),
        Country(isoCode: "PH", name: "Philippines", dialCode: "+63", flag: "🇵🇭"),
        Country(isoCode: "PN", name: "Pitcairn", dialCode: "+870", flag: "🇵🇳"),
        Country(isoCode: "PL", name: "Poland", dialCode: "+48", flag: "🇵🇱"),
        Country(isoCode: "PT", name: "Portugal", dialCode: "+351", flag: "🇵🇹"),
        Country(isoCode: "PR", name: "Puerto Rico", dialCode: "+1", flag: "🇵🇷"),
        Country(isoCode: "QA", name: "Qatar", dialCode: "+974", flag: "🇶🇦"),
        Country(isoCode: "CG", name: "Republic of the Congo", dialCode: "+242", flag: "🇨🇬"),
        Country(isoCode: "RE", name: "Reunion", dialCode: "+262", flag: "🇷🇪"),
        Country(isoCode: "RO", name: "Romania", dialCode: "+40", flag: "🇷🇴"),
        Country(isoCode: "RU", name: "Russia", dialCode: "+7", flag: "🇷🇺"),
        Country(isoCode: "RW", name: "Rwanda", dialCode: "+250", flag: "🇷🇼"),
        Country(isoCode: "BL", name: "Saint Barthelemy", dialCode: "+590", flag: "🇧🇱"),
        Country(isoCode: "SH", name: "Saint Helena", dialCode: "+290", flag: "🇸🇭"),
        Country(isoCode: "KN", name: "Saint Kitts and Nevis", dialCode: "+1", flag: "🇰🇳"),
        Country(isoCode: "LC", name: "Saint Lucia", dialCode: "+1", flag: "🇱🇨"),
        Country(isoCode: "MF", name: "Saint Martin", dialCode: "+590", flag: "🇲🇫"),
        Country(isoCode: "PM", name: "Saint Pierre and Miquelon", dialCode: "+508", flag: "🇵🇲"),
        Country(isoCode: "VC", name: "Saint Vincent and the Grenadines", dialCode: "+1", flag: "🇻🇨"),
        Country(isoCode: "WS", name: "Samoa", dialCode: "+685", flag: "🇼🇸"),
        Country(isoCode: "SM", name: "San Marino", dialCode: "+378", flag: "🇸🇲"),
        Country(isoCode: "ST", name: "Sao Tome and Principe", dialCode: "+239", flag: "🇸🇹"),
        Country(isoCode: "SA", name: "Saudi Arabia", dialCode: "+966", flag: "🇸🇦"),
        Country(isoCode: "SN", name: "Senegal", dialCode: "+221", flag: "🇸🇳"),
        Country(isoCode: "RS", name: "Serbia", dialCode: "+381", flag: "🇷🇸"),
        Country(isoCode: "SC", name: "Seychelles", dialCode: "+248", flag: "🇸🇨"),
        Country(isoCode: "SL", name: "Sierra Leone", dialCode: "+232", flag: "🇸🇱"),
        Country(isoCode: "SG", name: "Singapore", dialCode: "+65", flag: "🇸🇬"),
        Country(isoCode: "SX", name: "Sint Maarten", dialCode: "+1", flag: "🇸🇽"),
        Country(isoCode: "SK", name: "Slovakia", dialCode: "+421", flag: "🇸🇰"),
        Country(isoCode: "SI", name: "Slovenia", dialCode: "+386", flag: "🇸🇮"),
        Country(isoCode: "SB", name: "Solomon Islands", dialCode: "+677", flag: "🇸🇧"),
        Country(isoCode: "SO", name: "Somalia", dialCode: "+252", flag: "🇸🇴"),
        Country(isoCode: "ZA", name: "South Africa", dialCode: "+27", flag: "🇿🇦"),
        Country(isoCode: "KR", name: "South Korea", dialCode: "+82", flag: "🇰🇷"),
        Country(isoCode: "SS", name: "South Sudan", dialCode: "+211", flag: "🇸🇸"),
        Country(isoCode: "ES", name: "Spain", dialCode: "+34", flag: "🇪🇸"),
        Country(isoCode: "LK", name: "Sri Lanka", dialCode: "+94", flag: "🇱🇰"),
        Country(isoCode: "SD", name: "Sudan", dialCode: "+249", flag: "🇸🇩"),
        Country(isoCode: "SR", name: "Suriname", dialCode: "+597", flag: "🇸🇷"),
        Country(isoCode: "SJ", name: "Svalbard and Jan Mayen", dialCode: "+47", flag: "🇸🇯"),
        Country(isoCode: "SZ", name: "Swaziland", dialCode: "+268", flag: "🇸🇿"),
        Country(isoCode: "SE", name: "Sweden", dialCode: "+46", flag: "🇸🇪"),
        Country(isoCode: "CH", name: "Switzerland", dialCode: "+41", flag: "🇨🇭"),
        Country(isoCode: "SY", name: "Syria", dialCode: "+963", flag: "🇸🇾"),
        Country(isoCode: "TW", name: "Taiwan", dialCode: "+886", flag: "🇹🇼"),
        Country(isoCode: "TJ", name: "Tajikistan", dialCode: "+992", flag: "🇹🇯"),
        Country(isoCode: "TZ", name: "Tanzania", dialCode: "+255", flag: "🇹🇿"),
        Country(isoCode: "TH", name: "Thailand", dialCode: "+66", flag: "🇹🇭"),
        Country(isoCode: "TG", name: "Togo", dialCode: "+228", flag: "🇹🇬"),
        Country(isoCode: "TK", name: "Tokelau", dialCode: "+690", flag: "🇹🇰"),
        Country(isoCode: "TO", name: "Tonga", dialCode: "+676", flag: "🇹🇴"),
        Country(isoCode: "TT", name: "Trinidad and Tobago", dialCode: "+1", flag: "🇹🇹"),
        Country(isoCode: "TN", name: "Tunisia", dialCode: "+216", flag: "🇹🇳"),
        Country(isoCode: "TR", name: "Turkey", dialCode: "+90", flag: "🇹🇷"),
        Country(isoCode: "TM", name: "Turkmenistan", dialCode: "+993", flag: "🇹🇲"),
        Country(isoCode: "TC", name: "Turks and Caicos Islands", dialCode: "+1", flag: "🇹🇨"),
        Country(isoCode: "TV", name: "Tuvalu", dialCode: "+688", flag: "🇹🇻"),
        Country(isoCode: "VI", name: "U.S. Virgin Islands", dialCode: "+1", flag: "🇻🇮"),
        Country(isoCode: "UG", name: "Uganda", dialCode: "+256", flag: "🇺🇬"),
        Country(isoCode: "UA", name: "Ukraine", dialCode: "+380", flag: "🇺🇦"),
        Country(isoCode: "AE", name: "United Arab Emirates", dialCode: "+971", flag: "🇦🇪"),
        Country(isoCode: "GB", name: "United Kingdom", dialCode: "+44", flag: "🇬🇧"),
        Country(isoCode: "US", name: "United States", dialCode: "+1", flag: "🇺🇸"),
        Country(isoCode: "UY", name: "Uruguay", dialCode: "+598", flag: "🇺🇾"),
        Country(isoCode: "UZ", name: "Uzbekistan", dialCode: "+998", flag: "🇺🇿"),
        Country(isoCode: "VU", name: "Vanuatu", dialCode: "+678", flag: "🇻🇺"),
        Country(isoCode: "VA", name: "Vatican", dialCode: "+379", flag: "🇻🇦"),
        Country(isoCode: "VE", name: "Venezuela", dialCode: "+58", flag: "🇻🇪"),
        Country(isoCode: "VN", name: "Vietnam", dialCode: "+84", flag: "🇻🇳"),
        Country(isoCode: "WF", name: "Wallis and Futuna", dialCode: "+681", flag: "🇼🇫"),
        Country(isoCode: "EH", name: "Western Sahara", dialCode: "+212", flag: "🇪🇭"),
        Country(isoCode: "YE", name: "Yemen", dialCode: "+967", flag: "🇾🇪"),
        Country(isoCode: "ZM", name: "Zambia", dialCode: "+260", flag: "🇿🇲"),
        Country(isoCode: "ZW", name: "Zimbabwe", dialCode: "+263", flag: "🇿🇼")
    ]
}
